### ISSUE TITLE
Sen2cor 3 Install Timeout

### ISSUE THREAD

**Issue by marujore** [senbox-org/sen2like#12]
Hi, I was trying to use Sen2cor but getting Timeout.

`python sen2cor3_download.py /my/dir/sen2cor/3.01/`

`Traceback (most recent call last):
  File "/home/my_user/git_hub/sen2like/sen2cor3/sen2cor3_download.py", line 41, in <module>
    download_from_sftp(hostname, port, username, password, remote_path, local_path)
  File "/home/my_user/sen2like/sen2cor3/sen2cor3_download.py", line 7, in download_from_sftp
    transport = paramiko.Transport((hostname, port))
  File "/home/my_user/anaconda3/envs/sen2like/lib/python3.10/site-packages/paramiko/transport.py", line 464, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to sftp.telespazio.fr: [Errno 110] Connection timed out`

**Comment by telespazio-tim** [comment]
Contact by email was made on 02/07/2024 to resolve the ftp downtime issue.
Sen2Cor3 is now available on request as indicated in https://github.com/senbox-org/sen2like/tree/master/sen2cor3.
